import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navigation from './(ui)/components/navigation/Navigation';
import './globals.css';
import Providers from './providers/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<ClerkProvider
			appearance={{
				variables: {
					// https://mycolor.space/?hex=%23141414&sub=1 --> Highlight Palette
					colorPrimary: '#068488',
				},
				elements: {
					card: {
						boxShadow: 'none',
						WebkitBoxShadow: 'none',
						border: `1px solid #e5e7eb`,
						borderRadius: '0.5rem',
					},
				},
			}}
		>
			<html lang='en' className='min-h-screen'>
				<body className={`grid ${inter.className}`}>
					<Providers>
						<Navigation />
						{children}
					</Providers>
				</body>
			</html>
		</ClerkProvider>
	);
}
